### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: '${CACTI_FOLDER}/data_log.csv'"

### ISSUE THREAD

**Issue by sei-cabidi** [facebookresearch/Project_FARSI#1]
Hello, I'm having an issue with running `simple_sim_run.py` when following the tutorial in the README. I get the following error:

```
python3 simple_sim_run.py 
case study:simple_sim_run
hw_sampling:{'mode': 'exact', 'population_size': 1, 'reduction': 'most_likely', 'accuracy_percentage': {'sram': {'latency': 1, 'energy': 1, 'area': 1, 'one_over_area': 1}, 'dram': {'latency': 1, 'energy': 1, 'area': 1, 'one_over_area': 1}, 'ic': {'latency': 1, 'energy': 1, 'area': 1, 'one_over_area': 1}, 'gpp': {'latency': 1, 'energy': 1, 'area': 1, 'one_over_area': 1}, 'ip': {'latency': 1, 'energy': 1, 'area': 1, 'one_over_area': 1}}}
budget set to:{'latency': {'SOC_example_1p_2r': 0.05}, 'area': 1.0, 'power': 1.0}
*****************************
***** YOU ASKED TO USE CACTI FOR POWER/AREA MODELING OF MEMORY SUBSYSTEM. MAKE SURE YOU HAVE CACTI INSTALLED ****
*****************************
sanity check failed with:  insanity name:bus_with_no_memLMEM_ic_2_1_ic_20_sr1_20
deactivated Bus with No memory error, since hardware graph was directly user generated/parsed 
sanity check failed with:  insanity name:bus_with_no_pesLMEM_ic_2_1_ic_21_sr2_21
deactivated Bus with No Bus error, since hardware graph was directly user generated/parsed 
Traceback (most recent call last):
  File "simple_sim_run.py", line 102, in <module>
    dse_hndlr = run_FARSI_only_simulation(result_folder, unique_suffix, db_input, hw_sampling, sw_hw_database_population["hw_graph_mode"])
  File "/home/Project_FARSI/top/main_FARSI.py", line 144, in run_FARSI_only_simulation
    dse_handler.explore_one_design()
  File "/home/Project_FARSI/DSE_utils/design_space_exploration_handler.py", line 242, in explore_one_design
    self.dse.explore_one_design()
  File "/home/Project_FARSI/DSE_utils/hill_climbing.py", line 2844, in explore_one_design
    self.init_sim_dp = self.so_far_best_sim_dp = self.eval_design(self.so_far_best_ex_dp, self.database)
  File "/home/Project_FARSI/DSE_utils/hill_climbing.py", line 2569, in eval_design
    sim_dp_pop_sample = list(map(lambda ex_dp_: self.sim_one_design(ex_dp_, database), ex_dp_pop_sample)) # evaluate the population sample
  File "/home/Project_FARSI/DSE_utils/hill_climbing.py", line 2569, in <lambda>
    sim_dp_pop_sample = list(map(lambda ex_dp_: self.sim_one_design(ex_dp_, database), ex_dp_pop_sample)) # evaluate the population sample
  File "/home/Project_FARSI/DSE_utils/hill_climbing.py", line 2427, in sim_one_design
    sim_dp = self.dh.convert_to_sim_des_point(ex_dp)
  File "/home/Project_FARSI/design_utils/des_handler.py", line 984, in convert_to_sim_des_point
    return SimDesignPoint(ex_dp.get_hardware_graph(), workload_to_blocks_map, workload_to_pe_block_schedule)
  File "/home/Project_FARSI/design_utils/design.py", line 2043, in __init__
    config.cacti_output_col_order)
  File "/home/Project_FARSI/misc/cacti_hndlr/cact_handlr.py", line 29, in __init__
    self.cacti_data_container = CactiDataContainer(cacti_data_log_file, input_col_order, output_col_order)
  File "/home/Project_FARSI/misc/cacti_hndlr/cact_handlr.py", line 113, in __init__
    self.prase_cached_data()
  File "/home/Project_FARSI/misc/cacti_hndlr/cact_handlr.py", line 118, in prase_cached_data
    file = open(self.cached_data_file_addr, "w")
FileNotFoundError: [Errno 2] No such file or directory: '${CACTI_FOLDER}/data_log.csv'
```

I do have CACTI installed under CACTI_FOLDER, but clearly `data_log.csv` does not exist.
```
ls $CACTI_FOLDER/
2DDRAM_Samsung2GbDDR2.cfg        cacti.i              farsi_gen.cfg         obj_dbg
2DDRAM_micron1Gb.cfg             cacti.mk             htree2.cc             parameter.cc
3DDRAM_Samsung3D8Gb_extened.cfg  cacti_interface.cc   htree2.h              parameter.h
README                           cacti_interface.h    io.cc                 powergating.cc
TSV.cc                           component.cc         io.h                  powergating.h
TSV.h                            component.h          lpddr.cfg             regression.test
Ucache.cc                        const.h              main.cc               router.cc
Ucache.h                         contention.dat       makefile              router.h
arbiter.cc                       crossbar.cc          mat.cc                sample_config_files
arbiter.h                        crossbar.h           mat.h                 subarray.cc
area.cc                          ddr3.cfg             memcad.cc             subarray.h
area.h                           decoder.cc           memcad.h              tech_params
bank.cc                          decoder.h            memcad_parameters.cc  technology.cc
bank.h                           dram.cfg             memcad_parameters.h   uca.cc
basic_circuit.cc                 extio.cc             memorybus.cc          uca.h
basic_circuit.h                  extio.h              memorybus.h           version_cacti.h
cache.cfg                        extio_technology.cc  nuca.cc               wire.cc
cacti                            extio_technology.h   nuca.h                wire.h
```

Is `data_log.csv` a file that should come with FARSI? Or should it be something automatically generated by CACTI?

Thank you

**Comment by zoghin** [comment]
Yes, I had the same problem.
